import {createAnimalManager} from './AnimalManager.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {ANIMAL_SCHEMA,animalSchema,animalKinds,isCustomKind,GROUP_LABELS,normalizeAnimalSettings,animalPreset,parseAnimalPreset} from '../animals/AnimalSettings.js';
import {createAnimalSystem} from '../animals/AnimalSystem.js';
import {createAnimalModel} from '../animals/AnimalModels.js';
import {ANIMAL_NAMES} from '../animals/design/AnimalSpecies.js';
import {readDesign,saveDesign} from './DesignStore.js';
import {animalPathClear} from '../animals/AnimalCollision.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),world=params.get('world')||'local-world',session=params.get('session')||'',draftKey=`ocean-animal-draft:${world}`;
let settings=normalizeAnimalSettings(),kind=animalSchema(params.get('species'))?params.get('species'):'orca',paused=false,follow=false,system,food=[],consumed=0,migrations=0,simSpeed=1,isolate=false;
try{settings=normalizeAnimalSettings(JSON.parse(localStorage.getItem(draftKey)||'null')||JSON.parse(localStorage.getItem(`ocean-animal-settings:${world}`)||'null')||{});}catch{}
try{const stored=await readDesign('settings:'+world);if(stored)settings=normalizeAnimalSettings(stored);}catch{}
function cacheSettings(){saveDesign('settings:'+world,settings).catch(()=>{$('status').textContent='Opslag mislukt. Exporteer je instellingen.';});try{if(Object.values(settings).some(s=>s?.design?.asset?.data.length>2000000))return;localStorage.setItem(draftKey,JSON.stringify(settings));}catch{}}
if(!settings[kind])kind='custom';
const scene=new THREE.Scene();scene.background=new THREE.Color('#12323e');scene.fog=new THREE.Fog('#12323e',100,420);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#12323e');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;$('viewport').append(renderer.domElement);
const camera=new THREE.PerspectiveCamera(42,1,.1,650),orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxDistance=340;orbit.minDistance=1;
scene.add(new THREE.HemisphereLight(0xa9e6ff,0x4c5540,2.2));const sun=new THREE.DirectionalLight(0xffefd3,3);sun.position.set(10,30,15);scene.add(sun);const rim=new THREE.DirectionalLight(0x72e9fb,2);rim.position.set(-10,8,-12);scene.add(rim);
const sand=new THREE.Mesh(new THREE.PlaneGeometry(650,650,1,1),new THREE.MeshStandardMaterial({color:0x8c9980,roughness:.95}));sand.rotation.x=-Math.PI/2;sand.position.y=-22;scene.add(sand);
const water=new THREE.Mesh(new THREE.PlaneGeometry(650,650),new THREE.MeshStandardMaterial({color:0x5ba9b2,transparent:true,opacity:.10,side:THREE.DoubleSide,depthWrite:false}));water.rotation.x=-Math.PI/2;water.position.y=19.8;scene.add(water);
const grid=new THREE.GridHelper(288,24,0x709895,0x34585c);grid.position.y=-21.95;scene.add(grid);
const boundary=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(Array.from({length:6},(_,i)=>new THREE.Vector3(144*Math.cos(i*Math.PI/3),-21.8,144*Math.sin(i*Math.PI/3)))),new THREE.LineBasicMaterial({color:0x5ecba2}));scene.add(boundary);
const foodGeo=new THREE.SphereGeometry(1,12,8),foodMat=new THREE.MeshStandardMaterial({color:0xdf965d,roughness:.6});
function dropFood(){const primary=[...system.models.values()].find(m=>m.root.userData.animalKind==='orca')?.root;const p=primary?.position||new THREE.Vector3();const fish=new THREE.Mesh(foodGeo,foodMat);fish.scale.set(1.2,.4,.4);fish.position.copy(p).add(new THREE.Vector3(16,2,3));fish.userData={imported:true,health:0,vitalState:'sinking'};scene.add(fish);food.push(fish);}
function frameModel(){const rows=[...system.models.values()];const first=rows[0]?.root;if(!first||(first.userData.importedAnimal&&!rows[0].bounds))return;const box=new THREE.Box3().setFromObject(first),size=box.getSize(new THREE.Vector3()).length();orbit.target.copy(first.position);camera.position.copy(first.position).add(new THREE.Vector3(size*.7,size*.32,size*1.05));camera.lookAt(orbit.target);orbit.update();}
function setup(){system?.dispose();for(const f of food)scene.remove(f);food=[];consumed=0;migrations=0;const test=normalizeAnimalSettings(settings),scenario=$('scenario').value;simSpeed=scenario==='migration'?8:1;
 if(scenario==='food'){test.orca.feeding=true;if(kind!=='orca'){kind='orca';renderControls();}test.orca.hungerRate=Math.max(test.orca.hungerRate,3);}
 if(scenario==='migration'){if(!['whale','turtle'].includes(kind)){kind='whale';renderControls();}test[kind].residence=60;}
 if(scenario==='age'){kind='turtle';test.turtle.age=Number($('testAge').value);renderControls();}
 $('ageLabel').hidden=scenario!=='age';$('feed').hidden=kind!=='orca';$('hungry').hidden=kind!=='orca';
 system=createAnimalSystem({settings:test,factory:createAnimalModel,worldId:'studio-A',terrain:()=>-22,clearPath:(r,a,b,e,p)=>animalPathClear(r,a,b,e,p,{terrain:()=>-22}),corpses:()=>food,consume:f=>{scene.remove(f);food=food.filter(x=>x!==f);consumed++;},attach:m=>scene.add(m.root),detach:m=>scene.remove(m.root),neighbors:id=>[{id:id==='studio-A'?'studio-B':'studio-A',side:id==='studio-A'?3:0}],onMigration:event=>{migrations++;setTimeout(()=>{system.activateWorld(event.to);frameModel();},0);}});
 system.add(kind,[0,kind==='stingray'?-20:kind==='whale'?0:-5,0],0);if(scenario==='food'){system.add('turtle',[22,-5,8],0);for(const r of system.records.values())if(r.kind==='orca')r.hunger=70;dropFood();}
 if(scenario==='migration')for(const r of system.records.values())r.residence=57;
 for(const m of system.models.values())m.ready?.then(()=>{if([...system.models.values()].includes(m))frameModel();}).catch(e=>{$('status').textContent=e.message;});
 frameModel();$('scenarioInfo').textContent=({model:'Vrij zwemmen met je huidige instellingen. Draaien en zoomen verandert alleen de camera.',food:'Proef met moeder, jong, jonge schildpadden en dode importvis. Levende importvissen worden nooit gegeten. De tijdelijke proefoptie verandert je opgeslagen instellingen niet.',migration:'Versnelde proef: 8× simulatietijd, vertrek na 60 seconden. Identiteit en schildpadleeftijd blijven bij aankomst behouden.',age:'Leeftijdsvoorbeeld: bekijk grootte, schild, kleur, groepsgrootte en flipperslag. De leeftijdsschuif is alleen voor deze proef.'})[scenario];
}
function renderControls(){const query=new URLSearchParams(location.search);query.set('species',kind);query.set('from','studio');$('openSculptWorkbench').href='workbench.html?'+query;const nav=$('species');nav.replaceChildren();for(const [key,name] of Object.entries({...ANIMAL_NAMES,...Object.fromEntries(animalKinds(settings).filter(isCustomKind).map(k=>[k,settings[k].design?.name||'Eigen dier']))})){const btn=document.createElement('button');btn.textContent=name;btn.classList.toggle('active',key===kind);btn.onclick=()=>{kind=key;$('scenario').value='model';renderControls();setup();};nav.append(btn);}
 $('controls').replaceChildren();if(settings[kind].design?.asset){const label=document.createElement('label');label.textContent='Lengte in oceaan (m)';const input=document.createElement('input');input.id='import-world-length';input.type='number';input.min=.05;input.max=30;input.step=.05;input.value=settings[kind].design.worldLength;input.onchange=()=>{settings[kind].design.worldLength=Math.max(.05,Math.min(30,Number(input.value)||.05));input.value=settings[kind].design.worldLength;cacheSettings();system.configure(settings);for(const m of system.models.values())m.ready?.then(frameModel).catch(()=>{});};label.append(input);$('controls').append(label);}const groups=new Map();for(const [key,s] of Object.entries(animalSchema(kind,settings))){if(settings[kind].design?.asset&&s.group==='Model')continue;if(!groups.has(s.group)){const details=document.createElement('details');details.open=true;const summary=document.createElement('summary');summary.textContent=s.group;details.append(summary);$('controls').append(details);groups.set(s.group,details);}const row=document.createElement('div');row.className='control';const label=document.createElement('label');label.textContent=s.label;label.htmlFor='setting-'+key;row.append(label);let input;
 if(s.type==='boolean'){input=document.createElement('input');input.type='checkbox';input.checked=settings[kind][key];}else if(s.type==='select'){input=document.createElement('select');for(const v of s.options){const o=document.createElement('option');o.value=v;o.textContent=GROUP_LABELS[v]||v;input.append(o);}input.value=settings[kind][key];}else{input=document.createElement('input');input.type='number';input.min=s.min;input.max=s.max;input.step=s.step;input.value=settings[kind][key];const slider=document.createElement('input');slider.type='range';slider.min=s.min;slider.max=s.max;slider.step=s.step;slider.value=input.value;slider.setAttribute('aria-label',s.label);slider.oninput=()=>{input.value=slider.value;change();};row.append(slider);input.oninput=()=>{slider.value=input.value;change();};}
 input.id='setting-'+key;input.dataset.setting=key;row.insertBefore(input,row.children[1]||null);const change=()=>{settings[kind][key]=s.type==='boolean'?input.checked:s.type==='select'&&typeof s.value==='string'?input.value:Number(input.value);settings=normalizeAnimalSettings(settings);if(settings[kind].design)settings[kind].design.behavior=Object.fromEntries(Object.entries(settings[kind]).filter(([key])=>key!=='design'&&animalSchema(kind,settings)[key]?.group!=='Model'));cacheSettings();if($('scenario').value==='model')system.configure(settings);else setup();};if(s.type!=='number')input.onchange=change;groups.get(s.group).append(row);}}
$('preset').onchange=()=>{if($('preset').value==='default')return;settings=animalPreset($('preset').value);cacheSettings();renderControls();setup();};$('reset').onclick=()=>{settings[kind]=normalizeAnimalSettings()[kind]||{...normalizeAnimalSettings().custom,design:settings[kind].design};renderControls();setup();cacheSettings();};
$('isolate').onclick=()=>{isolate=!isolate;$('isolate').classList.toggle('active',isolate);$('isolate').setAttribute('aria-pressed',isolate);};$('scenario').onchange=setup;$('testAge').oninput=()=>{$('ageValue').textContent=$('testAge').value+' jaar';setup();};$('restart').onclick=setup;$('camera').onclick=()=>{follow=false;frameModel();};$('follow').onclick=()=>{follow=!follow;$('follow').classList.toggle('active',follow);};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Verder':'Pauze';};$('feed').onclick=dropFood;$('hungry').onclick=()=>{for(const r of system.records.values())if(r.kind==='orca')r.hunger=85;};
$('export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({format:'ocean-animal-studio-v1',settings},null,2)],{type:'application/json'}));a.download='animal-studio-preset.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};$('import').onchange=async()=>{try{settings=parseAnimalPreset(await $('import').files[0].text());cacheSettings();renderControls();setup();$('status').textContent='Instellingen geïmporteerd.';}catch(error){$('status').textContent=error.message;}$('import').value='';};

const channel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('ocean-animal-studio'):null;channel?.addEventListener('message',({data})=>{if(data?.type==='animal-settings-result'&&data.world===world&&data.session===session)$('status').textContent=data.message;});
$('apply').onclick=()=>{const payload={type:'animal-settings',world,session,settings,activeKind:kind,requestId:Date.now()};cacheSettings();try{if(Object.values(settings).some(s=>s?.design?.asset?.data.length>2000000))throw Error('Groot model');localStorage.setItem(`ocean-animal-pending:${world}`,JSON.stringify(payload));}catch{if(!session){$('status').textContent='Open de studio vanuit je oceaan om grote modellen toe te passen.';return;}}channel?.postMessage(payload);$('status').textContent=session?'Instellingen verzonden naar je geopende oceaan.':'Open de studio vanuit Design in je oceaan om de instellingen daar toe te passen.';};
new ResizeObserver(()=>{const el=$('viewport');renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();if(system)frameModel();}).observe($('viewport'));
const managerContainer=document.createElement('section');document.querySelector('aside').append(managerContainer);const manager=createAnimalManager(managerContainer,{getSettings:()=>settings,applySettings:next=>{settings=next;cacheSettings();renderControls();setup();},release:next=>{kind=next;renderControls();setup();$('apply').click();},remove:next=>system.removeKind(next),edit:next=>{kind=next;renderControls();setup();},status:text=>$('status').textContent=text});
renderControls();setup();let previous=performance.now(),lastStats=0;function tick(now){requestAnimationFrame(tick);const dt=Math.min(.05,(now-previous)/1000);previous=now;if(!paused){for(let i=0;i<simSpeed;i++)system.update(dt,{quality:'high'});for(const f of [...food]){f.position.y-=dt*.3;if(f.position.y<-21.4){scene.remove(f);food=food.filter(x=>x!==f);}}}if(follow){const first=[...system.models.values()][0]?.root;if(first){const offset=camera.position.clone().sub(orbit.target);orbit.target.lerp(first.position,.06);camera.position.copy(orbit.target).add(offset);}}orbit.update();let firstModel=true;for(const model of system.models.values()){model.root.visible=!isolate||firstModel;firstModel=false;}renderer.render(scene,camera);if(now-lastStats>300){lastStats=now;const rows=[...system.records.values()],first=rows.find(r=>r.kind===kind),stats=[['Dieren',system.models.size],['Fase',({cruise:'Zwemt',ascend:'Stijgt',breathe:'Ademt',descend:'Duikt',migrate:'Migreert'})[first?.phase]||'Onderweg'],['Simulatietijd',Math.floor(system.time)+' s'],['Gegeten',consumed],['Oversteken',migrations]];if(kind==='orca')stats.push(['Honger',Math.round(first?.hunger||0)+'%'],['Reserve',Math.round(first?.reserve||0)+'%'],['Voedsel',Math.round(system.models.get(first?.id)?.root.userData.foodAvailability||0)+'%']);if(kind==='turtle')stats.push(['Leeftijd',(first?.age||0)+' jaar'],['Groepen',new Set(rows.filter(r=>r.kind==='turtle').map(r=>r.groupId)).size]);stats.push(['Driehoeken',renderer.info.render.triangles.toLocaleString('nl-NL')]);$('telemetry').replaceChildren(...stats.map(([label,value])=>{const el=document.createElement('div');el.className='stat';el.append(document.createTextNode(label));const strong=document.createElement('strong');strong.textContent=value;el.append(strong);return el;}));}}
requestAnimationFrame(tick);window.__animalStudio={get system(){return system;},get settings(){return settings;},renderer,scene,camera,setup};addEventListener('pagehide',()=>{system.dispose();channel?.close();orbit.dispose();renderer.dispose();foodGeo.dispose();foodMat.dispose();});
