import * as THREE from 'three';
import {importAnimalFiles} from '../animals/design/ImportedAsset.js';
import {createImportedAnimal} from '../graphics/ImportedAnimal.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {normalizeAnimalDesign,parseAnimalDesign,designPrompt,DESIGN_LIMITS} from '../animals/design/AnimalDesign.js';
import {orcaRig} from '../animals/design/AnimalRig.js';
import {ANIMAL_SCHEMA,normalizeAnimalSettings} from '../animals/AnimalSettings.js';
import {createDesignedOrca} from '../graphics/DesignedAnimal.js';
import {ANIMAL_NAMES,IMPORT_LENGTHS,IMPORT_SPEEDS} from '../animals/design/AnimalSpecies.js';
import {readDesign,saveDesign,saveModel,listModels} from './DesignStore.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),world=params.get('world')||'local-world',session=params.get('session')||'',draftKey=`${world}:workbench`,initialSpecies=ANIMAL_NAMES[params.get('species')]?params.get('species'):'orca';
let settings;try{settings=normalizeAnimalSettings(JSON.parse(localStorage.getItem(`ocean-animal-draft:${world}`)||localStorage.getItem(`ocean-animal-settings:${world}`)||'{}'));}catch{settings=normalizeAnimalSettings();}
try{const saved=await readDesign('settings:'+world);if(saved)settings=normalizeAnimalSettings(saved);}catch{}
let design=normalizeAnimalDesign(settings[initialSpecies].design||{}),model,tab='sculpt',playing=false,time=0,tool='add',workerId=0,activeId=0,history=[],future=[],references=[],proposal=null,saveTimer,strokeStart=null,strokeDirty=false,lastPoint=null,building=false,disposed=false,lastSurface=null,lastRebuild=0;
try{const stored=await readDesign(draftKey)||await readDesign(`${world}:orca`);if(params.get('from')==='studio'&&settings[initialSpecies].design)design=normalizeAnimalDesign(settings[initialSpecies].design);else if(stored)design=normalizeAnimalDesign(stored);}catch{message('Conceptopslag is niet beschikbaar. Exporteer je ontwerp om het te bewaren.');}
$('back').href='./'+location.search;$('import-species').value=design.asset?design.species:initialSpecies;
const scene=new THREE.Scene();scene.background=new THREE.Color('#102a35');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('viewport').append(renderer.domElement);
const camera=new THREE.PerspectiveCamera(38,1,.1,400),orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.minDistance=5;orbit.maxDistance=160;orbit.target.set(0,1,0);
scene.add(new THREE.HemisphereLight(0xcdefff,0x3c514c,2.1));const key=new THREE.DirectionalLight(0xffefd4,3.4);key.position.set(15,22,18);scene.add(key);const rim=new THREE.DirectionalLight(0x8ddfe9,2.6);rim.position.set(-15,8,-20);scene.add(rim);
const grid=new THREE.GridHelper(100,20,0x4f7880,0x284a56);grid.position.y=-7;scene.add(grid);
const brush=new THREE.Mesh(new THREE.SphereGeometry(1,20,12),new THREE.MeshBasicMaterial({color:0x8fe1ba,transparent:true,opacity:.15,depthWrite:false,wireframe:true}));brush.visible=false;scene.add(brush);
const worker=new Worker(new URL('../animals/design/animal-mesh-worker.js',import.meta.url),{type:'module'});
worker.onmessage=({data})=>{if(data.id!==activeId||disposed)return;building=false;$('busy').hidden=true;if(data.error){message(data.error);return;}lastSurface=data.surface;installModel(data.surface);};
worker.onerror=()=>{building=false;$('busy').hidden=true;message('Oppervlak opbouwen mislukt. Herlaad de studio; je laatste concept blijft bewaard.');};
function message(text){$('message').textContent=text;}
function clone(value){if(!value.asset)return JSON.parse(JSON.stringify(value));const copy=JSON.parse(JSON.stringify({...value,asset:{...value.asset,data:undefined}}));copy.asset.data=value.asset.data;return copy;}
function checkpoint(){history.push(clone(design));let bytes=history.reduce((n,d)=>n+(d.asset?.data.length||0),0);while(history.length>24||(history.length>1&&bytes>32*1024*1024)){bytes-=history.shift().asset?.data.length||0;}future=[];syncHistory();}
function syncHistory(){$('undo').disabled=!history.length||!!proposal;$('redo').disabled=!future.length||!!proposal;}
function changed({mesh=true}={}){design=normalizeAnimalDesign(design);if(design.asset&&['sculpt','skin','ai'].includes(tab))setTab('import');queueSave();if(mesh)rebuild();else refreshMaterial();syncValues();}
function queueSave(){clearTimeout(saveTimer);$('saved').textContent='Concept bewaren…';saveTimer=setTimeout(()=>saveDesign(draftKey,clone(design)).then(()=>{$('saved').textContent='Concept bewaard op dit apparaat.';}).catch(()=>{$('saved').textContent='Opslag mislukt. Exporteer je ontwerp.';}),300);}
function rebuild(){if(design.asset&&!proposal){rebuildImported();return;}lastRebuild=performance.now();building=true;$('busy').hidden=false;activeId=++workerId;worker.postMessage({id:activeId,design:proposal?.candidate||design});}
function installModel(surface){const old=model;model=createDesignedOrca(proposal?.candidate||design,{surface,studio:true,clay:tab==='sculpt'&&$('clay').checked});scene.add(model.root);scene.add(model.helper);old?.helper.removeFromParent();old?.root.removeFromParent();old?.dispose();syncRig();showStats();}
function attachModel(next){const old=model;model=next;scene.add(model.root);scene.add(model.helper);old?.helper.removeFromParent();old?.root.removeFromParent();old?.dispose();syncRig();showStats();}
async function rebuildImported(){const id=activeId=++workerId;building=true;$('busy').hidden=false;const next=createImportedAnimal(design,{studio:true});try{await next.ready;if(id!==activeId||disposed){next.dispose();return;}design.asset.bounds=next.bounds;design.asset.clip=next.design.asset.clip;attachModel(next);view('side');syncImport();queueSave();}catch(e){next.dispose();message('Model laden mislukt: '+e.message);}finally{if(id===activeId){building=false;$('busy').hidden=true;}}}
function refreshMaterial(){if(design.asset){if(model)model.design.motion=normalizeAnimalDesign(design).motion;return;}if(lastSurface&&!building)installModel(lastSurface);else rebuild();}
function showStats(){if(!model)return;$('stats').replaceChildren(...[`${model.stats.triangles.toLocaleString('nl-NL')} driehoeken`,`${model.bones.length} botten`,`${design.strokes.length} sculptbewerkingen`,`${design.skin.paint.length} verfstreken`,`${design.worldLength.toFixed(1)} m in oceaan`].map(t=>{const el=document.createElement('span');el.textContent=t;return el;}));}
const formFields={length:['Ontwerplengte',32,48,.5],girth:['Rompvolume',.75,1.25,.01],head:['Kopbreedte',.8,1.2,.01],dorsal:['Rugvin',.55,1.2,.01],flippers:['Zijvinnen',.75,1.2,.01],flukes:['Staartbreedte',.75,1.2,.01]};
const skinFields={roughness:['Huidruwheid',.08,.95,.01],pores:['Fijne huidstructuur',0,1,.01],scars:['Littekens',0,1,.01],patchSize:['Oogvlekken',.65,1.35,.01]};
const motionFields={duration:['Duur zwemcyclus (s)',.8,12,.1],amplitude:['Staartuitslag',0,.55,.01],frequency:['Tempo',.2,3,.05],flipper:['Flipperbeweging',0,.65,.01],lag:['Vertraging langs staart',0,1.8,.05],roll:['Lichaamsrol',0,.15,.005]};
function controls(target,group,fields){for(const [field,[name,min,max,step]] of Object.entries(fields)){const label=document.createElement('label');label.append(document.createTextNode(name));const out=document.createElement('output'),input=document.createElement('input');input.type='range';input.id=`${group}-${field}`;input.min=min;input.max=max;input.step=step;input.value=design[group][field];out.id=`${group}-${field}-value`;out.textContent=input.value;label.append(out,input);input.onpointerdown=checkpoint;input.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))checkpoint();};input.oninput=()=>{design[group][field]=Number(input.value);out.textContent=input.value;if(group==='motion'){if(model)model.design.motion=normalizeAnimalDesign(design).motion;queueSave();syncValues();}else changed({mesh:group!=='skin'});};$(target).append(label);}}
controls('form-controls','form',formFields);controls('skin-controls','skin',skinFields);controls('motion-controls','motion',motionFields);
for(const [field,name] of Object.entries({dark:'Donkere huid',light:'Lichte huid',saddle:'Zadelvlek'})){const label=document.createElement('label');label.append(document.createTextNode(name));const input=document.createElement('input');input.type='color';input.id='skin-'+field;input.value=design.skin[field];input.onchange=()=>{checkpoint();design.skin[field]=input.value;changed({mesh:false});};label.append(input);$('skin-controls').prepend(label);}
function syncValues(){syncImport();$('design-name').value=design.name;$('worldLength').value=design.worldLength;$('length-value').textContent=design.worldLength.toFixed(1)+' m';$('resolution').value=String(design.resolution);$('timeline').max=cycleDuration();for(const group of ['form','skin','motion'])for(const key of Object.keys(design[group])){const input=$(`${group}-${key}`);if(input)input.value=design[group][key];const out=$(`${group}-${key}-value`);if(out)out.textContent=design[group][key];}$('key-info').textContent=`${design.motion.keys.length} referentiehoudingen in deze cyclus.`;syncHistory();}
function syncRig(){if(!model)return;model.helper.visible=tab==='rig'&&$('show-rig').checked;const selected=$('bone').value;$('bone').replaceChildren(...model.bones.map(b=>{const option=document.createElement('option');option.value=b.name;option.textContent=b.name;return option;}));if([...$('bone').options].some(o=>o.value===selected))$('bone').value=selected;}
function setTab(next){if(proposal){message('Gebruik het AI-voorstel of ga terug naar je ontwerp voordat je verder bewerkt.');return;}if(design.asset&&['sculpt','skin','ai'].includes(next))next='import';tab=next;playing=false;for(const btn of document.querySelectorAll('[data-tab]'))btn.classList.toggle('active',btn.dataset.tab===tab);for(const panel of document.querySelectorAll('[data-panel]'))panel.hidden=panel.dataset.panel!==tab;$('stage-label').textContent=`${tab.toUpperCase()} · ${design.asset?'GEÏMPORTEERD MODEL':'ORKA'}`;$('play').textContent='Test zwemmen';brush.visible=false;if(design.asset)syncRig();else rebuild();}
for(const btn of document.querySelectorAll('[data-tab]'))btn.onclick=()=>setTab(btn.dataset.tab);
for(const btn of document.querySelectorAll('[data-brush]'))btn.onclick=()=>{tool=btn.dataset.brush;for(const b of document.querySelectorAll('[data-brush]'))b.classList.toggle('active',b===btn);};
$('design-name').onchange=()=>{checkpoint();design.name=$('design-name').value;queueSave();};$('worldLength').onpointerdown=checkpoint;$('worldLength').oninput=()=>{design.worldLength=Number($('worldLength').value);syncValues();showStats();queueSave();};$('resolution').onchange=()=>{checkpoint();design.resolution=Number($('resolution').value);changed();};$('clay').onchange=rebuild;$('show-rig').onchange=syncRig;
$('brush-radius').oninput=()=>{$('radius-value').textContent=$('brush-radius').value;};$('radius-value').textContent=$('brush-radius').value;
$('reset-form').onclick=()=>{checkpoint();design.form=normalizeAnimalDesign().form;design.strokes=[];changed();};$('clear-paint').onclick=()=>{checkpoint();design.skin.paint=[];changed({mesh:false});};$('clear-texture').onclick=()=>{checkpoint();design.skin.texture=null;changed({mesh:false});};
$('undo').onclick=()=>{if(!history.length||proposal)return;future.push(clone(design));design=history.pop();changed();};$('redo').onclick=()=>{if(!future.length||proposal)return;history.push(clone(design));design=future.pop();changed();};
function view(direction){const distance=(design.asset?Math.max(40,...design.asset.bounds.map(v=>v*80)):design.form.length)*1.65;orbit.maxDistance=design.asset?800:160;orbit.target.set(0,1,0);camera.up.set(0,1,0);if(direction==='top'){camera.up.set(0,0,-1);camera.position.set(0,distance,0);}else if(direction==='front')camera.position.set(distance,2,0);else camera.position.set(6,7,distance);camera.lookAt(orbit.target);orbit.update();}
$('view-side').onclick=()=>view('side');$('view-top').onclick=()=>view('top');$('view-front').onclick=()=>view('front');
$('play').onclick=()=>{playing=!playing;brush.visible=false;$('play').textContent=playing?'Pauze':'Test zwemmen';};$('timeline').oninput=()=>{playing=false;time=Number($('timeline').value);$('play').textContent='Test zwemmen';};
$('jaw').onclick=()=>{model?.openMouth();playing=true;};$('add-key').onclick=()=>{if(design.motion.keys.length>=DESIGN_LIMITS.keys){message('Maximaal 120 houdingen.');return;}checkpoint();const key={time:Math.min(time,design.motion.duration),bone:$('bone').value,rotation:['x','y','z'].map(a=>Number($('bone-'+a).value))};design.motion.keys=design.motion.keys.filter(k=>!(k.bone===key.bone&&Math.abs(k.time-key.time)<.02));design.motion.keys.push(key);changed({mesh:!design.asset});};$('clear-keys').onclick=()=>{checkpoint();design.motion.keys=[];changed({mesh:!design.asset});};
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();
function hit(event){if(!model||design.asset)return null;const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObject(model.mesh)[0]||null;}
function paintOrSculpt(event){const result=hit(event);if(!result){brush.visible=false;return false;}const p=model.root.worldToLocal(result.point.clone()),radius=Number($(tab==='skin'?'paint-radius':'brush-radius').value);brush.position.copy(result.point);brush.scale.setScalar(radius);brush.visible=true;if(!strokeStart)return false;if(lastPoint&&lastPoint.distanceTo(p)<radius*.28)return false;lastPoint=p;
 if(tab==='sculpt'){if(design.strokes.length>=DESIGN_LIMITS.strokes){message('Maximaal 500 sculptbewerkingen. Bewaar dit ontwerp en verfijn de basisvorm.');return false;}design.strokes.push({mode:tool,point:p.toArray(),radius,strength:Number($('brush-strength').value),mirror:$('mirror').checked});}
 else{if(design.skin.paint.length>=64){message('Maximaal 64 lokale verfstreken. Gebruik een skin-textuur voor uitgebreider schilderwerk.');return false;}design.skin.paint.push({point:p.toArray(),radius,color:$('paint-color').value,opacity:Number($('paint-opacity').value),mirror:$('paint-mirror').checked});}
 strokeDirty=true;return true;}
renderer.domElement.addEventListener('pointerdown',event=>{if(event.button!==0||event.altKey||playing||proposal||!['sculpt','skin'].includes(tab)||building)return;if(!hit(event))return;event.preventDefault();event.stopImmediatePropagation();orbit.enabled=false;renderer.domElement.setPointerCapture(event.pointerId);checkpoint();strokeStart=clone(design);strokeDirty=false;lastPoint=null;paintOrSculpt(event);},{capture:true});
renderer.domElement.addEventListener('pointermove',event=>{if(!playing&&['sculpt','skin'].includes(tab)&&!proposal){paintOrSculpt(event);}});
function endStroke(){if(!strokeStart)return;strokeStart=null;lastPoint=null;orbit.enabled=true;if(strokeDirty)changed({mesh:tab==='sculpt'});else{history.pop();syncHistory();}strokeDirty=false;}
renderer.domElement.addEventListener('pointerup',endStroke);renderer.domElement.addEventListener('pointercancel',endStroke);renderer.domElement.addEventListener('lostpointercapture',endStroke);renderer.domElement.addEventListener('pointerleave',()=>{if(!strokeStart)brush.visible=false;});
async function imageData(file,maxSize=1024,quality=.86){const bmp=await createImageBitmap(file),canvas=document.createElement('canvas');const scale=Math.min(1,maxSize/Math.max(bmp.width,bmp.height));canvas.width=Math.max(1,Math.round(bmp.width*scale));canvas.height=Math.max(1,Math.round(bmp.height*scale));canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);bmp.close();return canvas.toDataURL('image/jpeg',quality);}
$('skin-image').onchange=async()=>{try{const file=$('skin-image').files[0];if(!file)return;const texture=await imageData(file,2048,.85);if(texture.length>DESIGN_LIMITS.textureBytes)throw Error('Deze huid bevat te veel data. Gebruik een kleinere afbeelding.');checkpoint();design.skin.texture=texture;changed({mesh:false});message('Skin geïmporteerd. Controleer de aansluiting rondom vinnen en buik.');}catch(e){message(e.message);}$('skin-image').value='';};
function renderReferences(){$('reference-list').replaceChildren(...references.map(r=>{const f=document.createElement('figure'),img=document.createElement('img'),c=document.createElement('figcaption');img.src=r.data;img.alt=r.label;c.textContent=r.label;f.append(img,c);return f;}));}
$('references').onchange=async()=>{try{for(const f of $('references').files){if(references.length>=18)break;references.push({data:await imageData(f),label:f.name.slice(0,70)});}renderReferences();message(`${references.length} referenties toegevoegd. Deze blijven lokaal totdat je AI-analyse start.`);}catch(e){message(e.message);}$('references').value='';};
let videoURL=null;$('video-file').onchange=()=>{const f=$('video-file').files[0];if(!f)return;if(videoURL)URL.revokeObjectURL(videoURL);videoURL=URL.createObjectURL(f);$('reference-video').src=videoURL;$('reference-video').hidden=false;$('reference-video').onloadedmetadata=()=>{$('sample-video').disabled=false;message('Kies één zwemcyclus in het filmpje en neem de referentieframes.');};$('reference-video').onerror=()=>message('Deze browser kan dit filmpje niet afspelen. Gebruik MP4 of WebM.');};
$('sample-video').onclick=async()=>{const video=$('reference-video');if(!Number.isFinite(video.duration)||video.duration<=0){message('Het filmpje is nog niet geladen.');return;}const start=Math.max(0,Math.min(video.duration-.1,Number($('clip-start').value)||0)),duration=Math.max(.8,Math.min(12,Number($('clip-duration').value)||3.1,video.duration-start));$('sample-video').disabled=true;try{references=references.filter(r=>r.time===undefined).slice(0,6);video.pause();for(let i=0;i<12;i++){const t=Math.min(video.duration-.03,start+duration*i/12);await new Promise((resolve,reject)=>{if(Math.abs(video.currentTime-t)<.001&&video.readyState>=2){resolve();return;}const timer=setTimeout(()=>{video.removeEventListener('seeked',done);reject(Error('Videoframe laden duurt te lang.'));},5000);function done(){clearTimeout(timer);resolve();}video.addEventListener('seeked',done,{once:true});video.currentTime=t;});const canvas=document.createElement('canvas'),scale=Math.min(1,768/video.videoWidth);canvas.width=video.videoWidth*scale;canvas.height=video.videoHeight*scale;canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);references.push({data:canvas.toDataURL('image/jpeg',.82),time:Number((t-start).toFixed(3)),label:`Zwemcyclus ${Number((t-start).toFixed(2))} s`});}renderReferences();message('Twaalf beelden klaar voor AI-analyse. Dit is bewegingsinterpretatie, geen exacte motioncapture.');}catch(e){message(e.message);}finally{$('sample-video').disabled=false;}};
$('clear-references').onclick=()=>{references=[];renderReferences();};
$('ai-endpoint').value=localStorage.getItem('ocean-animal-ai-endpoint')|| (location.port==='8787'?location.origin+'/api/animal-design':'');
function previewProposal(candidate){if(design.asset){message('AI-sculptvoorstellen zijn alleen beschikbaar voor eigen sculpturen.');return;}if(proposal)design=proposal.original;proposal={original:clone(design),candidate:normalizeAnimalDesign(candidate)};$('proposal').hidden=false;$('proposal-info').textContent='AI-voorstel in beeld. Je huidige ontwerp blijft bewaard totdat je het voorstel gebruikt.';playing=false;syncHistory();rebuild();}
$('import-ai').onclick=()=>{try{previewProposal(parseAnimalDesign($('ai-json').value));}catch(e){message(e.message);}};
$('accept-ai').onclick=()=>{if(!proposal)return;design=proposal.original;checkpoint();design=proposal.candidate;proposal=null;$('proposal').hidden=true;changed();message('AI-ontwerp gebruikt. Vorm, huid en beweging blijven bewerkbaar.');};$('reject-ai').onclick=()=>{if(!proposal)return;design=proposal.original;proposal=null;$('proposal').hidden=true;rebuild();syncHistory();};
$('copy-prompt').onclick=async()=>{const prompt=designPrompt(design,$('instruction').value);try{await navigator.clipboard.writeText(prompt);message('Opdracht gekopieerd. Voeg in onze chat ook je afbeeldingen of filmpje toe.');}catch{$('ai-json').value=prompt;message('Selecteer en kopieer de ontwerpopdracht uit het tekstvak.');}};
$('generate').onclick=async()=>{const endpoint=$('ai-endpoint').value.trim();if(!endpoint){message('Koppel een AI-server of gebruik “Kopieer opdracht voor ChatGPT”. Er is nog geen AI-dienst aangesloten.');return;}let url;try{url=new URL(endpoint);if(url.protocol!=='https:'&&!(url.protocol==='http:'&&['localhost','127.0.0.1'].includes(url.hostname)))throw Error('Gebruik HTTPS of een lokale AI-server.');}catch(e){message(e.message);return;}$('generate').disabled=true;localStorage.setItem('ocean-animal-ai-endpoint',endpoint);message('AI analyseert de referenties en stelt vorm, huid en beweging voor…');try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({design,instruction:$('instruction').value,references}),signal:AbortSignal.timeout(180000)});const result=await response.json();if(!response.ok)throw Error(result.error||'AI-analyse mislukt.');previewProposal({...result.design,skin:{...result.design.skin,texture:design.skin.texture}});message('AI-voorstel klaar. Bekijk het dier en gebruik het voorstel als het klopt.');}catch(e){message(e.message);}finally{$('generate').disabled=false;}};
$('generate-skin').onclick=async()=>{const endpoint=$('ai-endpoint').value.trim();if(!endpoint){message('Koppel eerst de AI-server om een huid te laten tekenen.');return;}try{const url=new URL(endpoint);if(url.protocol!=='https:'&&!(url.protocol==='http:'&&['localhost','127.0.0.1'].includes(url.hostname)))throw Error('Gebruik HTTPS of een lokale AI-server.');url.pathname='/api/animal-skin';$('generate-skin').disabled=true;message('AI tekent een huidtextuur…');const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({design,instruction:$('instruction').value,references:references.filter(r=>r.time===undefined).slice(0,4)}),signal:AbortSignal.timeout(240000)});const result=await response.json();if(!response.ok)throw Error(result.error||'Skin tekenen mislukt.');const blob=await (await fetch(result.texture)).blob(),texture=await imageData(blob,2048,.85);previewProposal({...design,skin:{...design.skin,texture}});message('AI-skin klaar. Controleer het voorstel voordat je het gebruikt.');}catch(e){message(e.message);}finally{$('generate-skin').disabled=false;}};
$('export-design').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(design,null,2)],{type:'application/json'}));a.href=url;a.download=(design.name.replace(/[^a-zA-Z0-9_-]+/g,'-')||design.species)+'-animal-design.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import-design').onchange=async()=>{try{const f=$('import-design').files[0];if(!f)return;const next=parseAnimalDesign(await f.text());if(next.asset){const test=createImportedAnimal(next,{studio:true});try{await test.ready;next.asset.bounds=test.bounds;}finally{test.dispose();}}checkpoint();design=next;renderBehavior();proposal=null;$('proposal').hidden=true;changed();message('Dierontwerp geïmporteerd.');}catch(e){message(e.message);}$('import-design').value='';};
const channel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('ocean-animal-studio'):null;channel?.addEventListener('message',({data})=>{if(data?.type==='animal-settings-result'&&data.world===world&&data.session===session)message(data.message);});
async function currentSettings(){return normalizeAnimalSettings(await readDesign('settings:'+world)||settings);}
async function withDesign(){const next=await currentSettings();next[design.species]={...next[design.species],...design.behavior,design:clone(design)};settings=normalizeAnimalSettings(next);await saveDesign('settings:'+world,settings);return settings;}
$('apply').onclick=async()=>{if(building||proposal){message('Wacht op het model en gebruik eerst het AI-voorstel.');return;}try{await withDesign();const payload={type:'animal-settings',world,session,settings,activeKind:design.species,requestId:Date.now()};try{if(Object.values(settings).some(s=>s?.design?.asset?.data.length>2000000))throw Error('Groot model');localStorage.setItem(`ocean-animal-draft:${world}`,JSON.stringify(settings));localStorage.setItem(`ocean-animal-pending:${world}`,JSON.stringify(payload));}catch{if(!session||!channel)throw Error('Open de studio vanuit je oceaan om dit grote model rechtstreeks toe te passen. Je model blijft lokaal bewaard.');}channel?.postMessage(payload);message(session?'Ontwerp verzonden naar je geopende oceaan.':'Instellingen bewaard. Open de studio vanuit Design in je oceaan om dit dier toe te passen.');}catch(e){message('Toepassen mislukt: '+e.message);}};
function renderBehavior(){const panel=$('behavior-controls');panel.replaceChildren();if(!design.asset)return;design.behavior={...Object.fromEntries(Object.entries(ANIMAL_SCHEMA[design.species]).filter(([,v])=>v.group!=='Model').map(([key])=>[key,settings[design.species][key]])),...design.behavior};for(const [key,field] of Object.entries(ANIMAL_SCHEMA[design.species])){if(field.group==='Model')continue;const label=document.createElement('label'),input=document.createElement(field.type==='select'?'select':'input');label.append(document.createTextNode(field.label));input.id='behavior-'+key;if(field.type==='boolean'){input.type='checkbox';input.checked=design.behavior[key];}else if(field.type==='select'){for(const value of field.options){const o=document.createElement('option');o.value=value;o.textContent=value;input.append(o);}input.value=design.behavior[key];}else{input.type='number';input.min=field.min;input.max=field.max;input.step=field.step;input.value=design.behavior[key];}input.onchange=()=>{checkpoint();const value=field.type==='boolean'?input.checked:Number(input.value);const next=normalizeAnimalSettings({[design.species]:{[key]:value}})[design.species][key];design.behavior[key]=next;if(field.type!=='boolean')input.value=next;queueSave();};label.append(input);panel.append(label);}}
async function refreshLibrary(){const rows=await listModels();$('model-library').replaceChildren(...rows.map(row=>{const option=document.createElement('option');option.value=row.id;option.textContent=`${row.name} · ${ANIMAL_NAMES[row.species]} · ${row.worldLength} m`;return option;}));if(design.id)$('model-library').value=design.id;$('load-model').disabled=!rows.length;}
$('save-model').onclick=async()=>{if(building||proposal){message('Wacht totdat je model klaar is.');return;}try{design.id ||= crypto.randomUUID();design=normalizeAnimalDesign(design);await saveModel(clone(design));await saveDesign(draftKey,clone(design));await refreshLibrary();message(`${design.name} bewaard als ${ANIMAL_NAMES[design.species]}. Je vindt het bij Mijn modellen.`);}catch(e){message('Bewaren mislukt: '+e.message);}};
$('load-model').onclick=async()=>{try{const next=await readDesign('model:'+$('model-library').value);if(!next)throw Error('Model niet gevonden.');checkpoint();design=normalizeAnimalDesign(next);time=0;renderBehavior();syncValues();setTab(design.asset?'import':'sculpt');if(design.asset)rebuild();queueSave();message('Opgeslagen model geopend.');}catch(e){message(e.message);}};
$('import-species').onchange=()=>{if(!design.asset)return;checkpoint();design.species=$('import-species').value;design.behavior=undefined;renderBehavior();changed();};
$('import-length-number').onchange=()=>{checkpoint();design.worldLength=Math.max(.05,Math.min(30,Number($('import-length-number').value)||.05));syncValues();showStats();queueSave();};
$('test-behavior').onclick=async()=>{try{await withDesign();const query=new URLSearchParams(location.search);query.set('species',design.species);location.href='./?'+query;}catch(e){message(e.message);}};
refreshLibrary().catch(()=>{});renderBehavior();
function cycleDuration(){return design.asset?(model?.clips?.[design.asset.clip]?.duration||3.1):design.motion.duration;}
function syncImport(){
 const asset=design.asset; $('import-controls').hidden=!asset;$('rig-description').textContent=asset?'Pas botrotaties aan en bewaar houdingen op de tijdlijn. Deze beweging wordt over de meegeleverde animatie gelegd.':'20 botten sturen rug, staart, flippers en bek aan. De vorm blijft bewerkbaar.';
 for(const button of document.querySelectorAll('[data-tab]'))button.disabled=!!asset&&['sculpt','skin','ai'].includes(button.dataset.tab);
 for(const input of document.querySelectorAll('#motion-controls input, #jaw'))input.disabled=!!asset;for(const input of document.querySelectorAll('#bone-x, #bone-y, #bone-z, #add-key'))input.disabled=!!asset&&!model?.bones?.length;
 if(!asset){$('import-info').textContent='Er is nog geen extern model geïmporteerd.';return;}
 $('import-species').value=design.species;$('import-length-number').value=design.worldLength;$('import-name').value=design.name;$('import-length').value=design.worldLength;$('import-length-value').textContent=design.worldLength.toFixed(1)+' m';
 for(const key of ['author','license','source','speed'])$('import-'+key).value=asset[key];
 for(const [i,axis] of ['x','y','z'].entries())$('import-rotation-'+axis).value=Math.round(asset.rotation[i]*180/Math.PI);
 $('import-info').textContent=`${asset.filename} · ${(asset.data.length*(asset.kind==='glb'?.75:1)/1024/1024).toFixed(1)} MB · ${model?.bones.length||0} botten · ${model?.clips?.length||0} animaties`;
 $('import-clip').replaceChildren(...[{name:'Geen animatie',index:-1},...(model?.clips||[]).map((clip,index)=>({name:clip.name||`Animatie ${index+1}`,index}))].map(clip=>{const option=document.createElement('option');option.value=clip.index;option.textContent=clip.name;return option;}));$('import-clip').value=asset.clip;
 if(!model?.clips?.length)$('import-info').textContent+=' · Dit model bevat geen zwemanimatie.';
 $('timeline').max=cycleDuration();
}
async function importFiles(input){
 const previousDesign=design;let candidate;
 input.disabled=true;message('Model, textures en animaties laden…');
 try{const species=$('import-species').value,asset=await importAnimalFiles(input.files),defaults=normalizeAnimalSettings()[species],behavior=Object.fromEntries(Object.entries(ANIMAL_SCHEMA[species]).filter(([,v])=>v.group!=='Model').map(([key])=>[key,defaults[key]]));behavior.speed=IMPORT_SPEEDS[species];behavior.count=1;if(species==='turtle')behavior.age=defaults.adultAge;const next=normalizeAnimalDesign({...design,id:crypto.randomUUID(),species,behavior,worldLength:IMPORT_LENGTHS[species],motion:{...design.motion,keys:[]},name:asset.filename.replace(/\.(glb|gltf)$/i,''),asset});candidate=createImportedAnimal(next,{studio:true});await candidate.ready;
 if(disposed){candidate.dispose();return;}checkpoint();design=next;design.asset.bounds=candidate.bounds;design.asset.clip=candidate.design.asset.clip;design.motion.duration=candidate.clips[design.asset.clip]?.duration||3.1;renderBehavior();proposal=null;$('proposal').hidden=true;activeId=++workerId;building=false;$('busy').hidden=true;attachModel(candidate);candidate=null;time=0;setTab('import');syncValues();view('side');queueSave();message('Model geïmporteerd. Controleer de richting, kies een animatie en vul de maker en licentie in.');
 }catch(e){candidate?.dispose();design=previousDesign;message('Import mislukt: '+e.message);}finally{input.disabled=false;input.value='';}
}
$('import-model').onchange=()=>importFiles($('import-model'));$('import-folder').onchange=()=>importFiles($('import-folder'));
$('import-name').onchange=()=>{checkpoint();design.name=$('import-name').value;syncValues();queueSave();};
$('import-length').onpointerdown=checkpoint;$('import-length').oninput=()=>{design.worldLength=Number($('import-length').value);syncValues();showStats();queueSave();};
for(const key of ['author','license','source'])$('import-'+key).onchange=()=>{if(!design.asset)return;checkpoint();design.asset[key]=$('import-'+key).value;queueSave();};
for(const [i,axis] of ['x','y','z'].entries()){$('import-rotation-'+axis).onpointerdown=checkpoint;$('import-rotation-'+axis).onchange=()=>{if(!design.asset)return;design.asset.rotation[i]=Number($('import-rotation-'+axis).value)*Math.PI/180;rebuild();};}
$('import-speed').onpointerdown=checkpoint;$('import-speed').oninput=()=>{if(!design.asset)return;design.asset.speed=Number($('import-speed').value);if(model)model.design.asset.speed=design.asset.speed;queueSave();};
$('import-clip').onchange=()=>{if(!design.asset||building)return;checkpoint();design.asset.clip=Number($('import-clip').value);model.selectClip(design.asset.clip);design.motion.duration=model.clips[design.asset.clip]?.duration||3.1;time=0;syncImport();queueSave();};
$('remove-model').onclick=()=>{checkpoint();delete design.asset;design.species='orca';delete design.behavior;delete design.id;time=0;syncValues();setTab('sculpt');queueSave();message('Eigen sculptuur hersteld. Het geïmporteerde model kun je terughalen met Ongedaan maken.');};
new ResizeObserver(()=>{const el=$('viewport');renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();}).observe($('viewport'));
if(design.asset)tab='import';syncValues();view('side');setTab(tab);if(design.asset)rebuild();let previous=performance.now();function tick(now){if(disposed)return;requestAnimationFrame(tick);const dt=Math.min(.05,(now-previous)/1000);previous=now;if(strokeStart&&strokeDirty&&!building&&now-lastRebuild>200){if(tab==='sculpt')rebuild();else{lastRebuild=now;refreshMaterial();}}if(playing)time=(time+dt*(design.asset?.speed||1))%cycleDuration();if(model){if(design.asset){model.animate(0,time);}else if(playing||tab==='rig')model.animate(playing?dt:0,time);else for(const bone of model.bones)bone.rotation.set(0,0,0);if(tab==='rig'&&!playing){const bone=model.byName.get($('bone').value);if(bone&&document.activeElement?.id?.startsWith('bone-')){const e=new THREE.Euler(...['x','y','z'].map(a=>Number($('bone-'+a).value)));if(design.asset)bone.quaternion.multiply(new THREE.Quaternion().setFromEuler(e));else bone.rotation.copy(e);}}model.root.updateMatrixWorld(true);model.helper.updateMatrixWorld(true);}orbit.update();renderer.render(scene,camera);$('timeline').value=time;$('time-value').textContent=time.toFixed(2)+' s';}requestAnimationFrame(tick);
window.__animalWorkbench={get design(){return design;},get model(){return model;},get references(){return references;},get building(){return building;},scene,camera,renderer,view,setTab,rebuild,previewProposal,checkpoint,changed,get time(){return time;}};
addEventListener('pagehide',()=>{disposed=true;clearTimeout(saveTimer);saveDesign(draftKey,clone(design)).catch(()=>{});worker.terminate();channel?.close();orbit.dispose();model?.dispose();brush.geometry.dispose();brush.material.dispose();grid.geometry.dispose();grid.material.dispose();renderer.dispose();if(videoURL)URL.revokeObjectURL(videoURL);});
